### ISSUE TITLE
Is there a difference between Question #4 and Question #6

### ISSUE THREAD

**Issue by JoeMark17** [cmccann020/dbt_bestpractices#13]
In the [dbt_training](https://github.com/cmccann020/dbt_bestpractices/blob/master/training/README.md) markdown, it seems steps 4 and 6 are the same. Additionally, I have nothing to initialize at step 6, and already have the dbt files from step 4. Should I have something to initialize at this step?

**Comment by cmccann020** [comment]
There is and you pointed out an issue in the documentation. Going to fix now
