### ISSUE TITLE
Broken Link in Training ReadMe.md

### ISSUE THREAD

**Issue by JoeMark17** [cmccann020/dbt_bestpractices#3]
In the Training ReadMe.md file (dbt_bestpractices/training/README.md) there is a link at the bottom for "[recommended documentation](https://github.com/cmccann020/dbt_bestpractices/blob/master/training/Optional_Reading.md)" under the **Optional Steps** section. When I try to open the link I am presented with a github "404 repo not found" message. Do we need to obtain access to this repo?

**Comment by cmccann020** [comment]
Fixed. Link now leads to correct location in best_practices area.
